



                           
                           
                           
                           
                           
                           

                    




#confusion i dont think i send a json request , i think its just a string !
                           
                          
